### ISSUE TITLE
Use drat?

### ISSUE THREAD

**Issue by rstub** [jmsigner/rhr#1]
According to http://disq.us/p/22qxpqp the server that used to host `rhr` is currently down. Have you considered using [drat](https://cran.r-project.org/package=drat) to use GitHub for hosting?

**Comment by jmsigner** [comment]
Thanks for the suggestion @rstub . The following should work now:

```
install.packages("drat")
drat::addRepo("jmsigner")
install.packages("rhr")
```

**Comment by SimonDedman** [comment]
@ 18 Sept 2019:
`Warning in install.packages: package ‘jmsigner’ is not available (for R version 3.6.1)`
In case others were looking to try this approach.

**Comment by rstub** [comment]
@SimonDedman That should have read

```r
install.packages("drat")
drat::addRepo("jmsigner")
install.packages("rhr")
```

which is available.

**Comment by Rdigiovanni** [comment]
Is this package still working.  when I run it under GUi it crashes.  Is there a fix?

**Comment by rstub** [comment]
@Rdigiovanni You probably should create a separate issue for this and provide some more information about your environment, what you are trying to do, what is happening, ....
